### ISSUE TITLE
tau2paje segfaults with a valid trace file when node ids are not sequential

### ISSUE THREAD

**Issue by afarah1** [schnorr/akypuera#35]
tau2paje segfaults with a trace that `tau2otf` + `otf2paje` successfully convert.

    Program received signal SIGSEGV, Segmentation fault.
    0x0000000000403f58 in SendMessage (userData=0x0, time=3075295, sourceNodeToken=0, sourceThreadToken=0, destinationNodeToken=65535, 
        destinationThreadToken=0, messageSize=67108863, messageTag=65535, messageComm=63)
        at /home/afh/svn/akypuera/src/tau/tau2paje_handlers.c:219
    219       rank_last_time[destinationNodeToken] = time_to_seconds(time);
    (gdb) where
    #0  0x0000000000403f58 in SendMessage (userData=0x0, time=3075295, sourceNodeToken=0, sourceThreadToken=0, destinationNodeToken=65535, 
        destinationThreadToken=0, messageSize=67108863, messageTag=65535, messageComm=63)
        at /home/afh/svn/akypuera/src/tau/tau2paje_handlers.c:219
    #1  0x0000000000406049 in Ttf_ReadNumEvents (fileHandle=0x62af50, callbacks=..., numberOfEvents=<optimized out>) at TAU_tf.cpp:670
    #2  0x00000000004032c0 in main (argc=3, argv=0x7fffffffe0f8) at /home/afh/svn/akypuera/src/tau/tau2paje.c:101

This has to do with the way `tau2paje` grows `rank_last_time` - it assumes node ids are sequential. From `DefThread`:

    if (nodeid + 1 > total_number_of_ranks) {                                     
      total_number_of_ranks = nodeid + 1;                                         
      rank_last_time =                                                            
          realloc(rank_last_time, sizeof(double) * total_number_of_ranks);        
    }                                                                                                             
    rank_last_time[nodeid] = 0;  

An analysis with gdb shows that `65535` is passed suddenly, that is, there is no increase in source/destToken nor on messageTag. So the code above leads to a segfault later. I'm not sure why this number appears in the first time, though (overflow? there are no `unsigened short`s... `MPI_ANY_SOURCE` (-1 in OpenMPI)? there aren't any on Ondes...).

In any case, using a hash table (as it is currently used for states) instead of an array should fix the issue. The problem is that a double should be stored in the hashtable, and so some memory management would be required.

**Comment by schnorr** [comment]
Hello, can you make the offending TAU traces available somewhere?
